### ISSUE TITLE
Датчик THN132N

### ISSUE THREAD

**Issue by eagle23** [invandy/Oregon_NR#15]
Здравствуйте.
Имеется датчик THN132N.
Данные не могу получить. Как будто даже на захватывает пакеты.
Также имеются датчики  THGN132N и RTGN130 - работают великолепно.

Куда копать?

**Comment by invandy** [comment]
А он точно передаёт? Лампочка мигает так же, как у других датчиков?

**Comment by eagle23** [comment]
Да. Диод мигает каждые примерно 40 секунд. Датчик только купил ))

**Comment by eagle23** [comment]
Включал режим дебага, но датчика как будто нет в эфире совсем.

**Comment by eagle23** [comment]
Естественно, менял батарейки, канал, нажимал reset…

**Comment by invandy** [comment]
Честно скажу - не знаю. Если два других датчика принимаются исправно, а в положенные моменты времени от нового датчика не приходит даже мусор, значит он просто не передаёт.  Попробуйте проверить на подходящей оригинальной погодной станции.

**Comment by eagle23** [comment]
Видимо, это единственное, что осталось. Спасибо.
