### ISSUE TITLE
invalid library

### ISSUE THREAD

**Issue by Johnep101** [invandy/Oregon_NR#16]
Hi invandy,
firstly thank you for this project just what I need!
Please excuse my Russian I am using google translate!
When I compile all looks good but when I download to my ESP-12E module I get:- 
Invalid version '21.01.28' for library in: /Users/xxx/Documents/Arduino/Sketchbook/libraries/Oregon_NR-master
and nothing seems to work, do I need to connect an interrupt? I am using a simple 433MHz receiver?
Thank you!
John.

Привет invandy,
во первых спасибо за этот проект именно то что мне нужно!
Прошу прощения за мой русский язык, я использую гугл переводчик!
Когда я компилирую, все выглядит хорошо, но когда я загружаю в свой модуль ESP-12E, я получаю: -
Недопустимая версия 21 .01.28 для библиотеки в: / Users / xxx / Documents / Arduino / Sketchbook / libraries / Oregon_NR-master
и вроде ничего не работает, нужно ли подключать прерывание? Я использую простой приемник 433 МГц?
Спасибо!
Джон.

**Comment by invandy** [comment]
Hi. John.
Incorrect version error is just an annoyng message and does'n affect on sketch executinon :). I just fixed it.
As for "nothing seems to work" - if you connect your receiver to proper pin you have to catch at least trash packets periodically. Oregon_NR object declaration is to connect interrupt by itself. I think so...

**Comment by Johnep101** [comment]
wow mega fast response THANK YOU!
I will let you know how I get on !

вау мега быстрый ответ СПАСИБО!
Я дам вам знать, как у меня дела!

**Comment by Johnep101** [comment]
Compiled and uploaded no problem Thank you!

**Comment by Johnep101** [comment]
Now I feed the signal into the right pin on my E-12 module all works. 
thank you this is excellent code!

Теперь я подаю сигнал на правый контакт на моем модуле E-12, все работает.
спасибо, это отличный код!
