### ISSUE TITLE
esp8266 with mqtt

### ISSUE THREAD

**Issue by kroon040** [invandy/Oregon_NR#3]
Hi,

I like it, is it possible to add mqtt support on the esp8266, to the values are send to it?

regards Richard

**Comment by invandy** [comment]
Do not understand what are you talking about...  This library is for receiveng data from Oregon wireless sensors only.

**Comment by Saphareas** [comment]
@kroon040 Hey,
I've added an MQTT example in [my fork](https://github.com/Saphareas/Oregon_NR/blob/master/examples/MQTT_Publish/MQTT_Publish.ino)

**Comment by kroon040** [comment]
I will try it. I will connect an RXB6 to the ESP8266. Where in the code can I find the data pint to the ESP8266.

Also , can you add the example for mqtt with username and password for the mqtt connection?

**Comment by kroon040** [comment]
I found in the code pins, and it works . Now I try to add username/password to mqtt

**Comment by kroon040** [comment]
successfully added username and password. So I'm happy
